In [ ]:
import numpy as np
import pandas as pd


In [ ]:
df =pd.read_csv("/content/spam.csv")

In [ ]:
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
df['spam'] = df["Category"].apply(lambda x: 1 if x =="spam" else 0 )

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam)

In [ ]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [ ]:
X_train.shape

(4179,)

In [ ]:
X_test.shape

(1393,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
v= CountVectorizer()

In [ ]:
X_train_cv = v.fit_transform(X_train.values)

In [ ]:
X_train_cv.shape

(4179, 7472)

In [ ]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_cv.shape

(4179, 7472)

In [ ]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [ ]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'bui

In [ ]:
X_train_np = X_train_cv.toarray()

In [ ]:
X_train_np[:40]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train_np.shape

(4179, 7472)

In [ ]:
v.vocabulary_

{'forwarded': 2872,
 'from': 2924,
 '448712404000': 484,
 'please': 5050,
 'call': 1557,
 '08712404000': 106,
 'immediately': 3482,
 'as': 1064,
 'there': 6565,
 'is': 3601,
 'an': 938,
 'urgent': 6938,
 'message': 4285,
 'waiting': 7092,
 'for': 2849,
 'you': 7430,
 'where': 7216,
 'my': 4490,
 'boytoy': 1434,
 'miss': 4336,
 'what': 7205,
 'happened': 3213,
 'ultimately': 6859,
 'tor': 6720,
 'motive': 4426,
 'tui': 6806,
 'achieve': 772,
 'korli': 3819,
 'bears': 1239,
 'pic': 5002,
 'nick': 4589,
 'and': 942,
 'tom': 6688,
 'pete': 4977,
 'dick': 2228,
 'in': 3498,
 'fact': 2662,
 'all': 896,
 'types': 6842,
 'try': 6792,
 'gay': 2991,
 'chat': 1689,
 'with': 7278,
 'photo': 4996,
 'upload': 6925,
 '08718730666': 147,
 '10p': 258,
 'min': 4310,
 'stop': 6249,
 'texts': 6534,
 '08712460324': 109,
 'we': 7145,
 're': 5367,
 'getting': 3027,
 'worried': 7329,
 'over': 4831,
 'here': 3292,
 'derek': 2194,
 'taylor': 6462,
 'have': 3238,
 'already': 908,
 'assumed': 1087,
 'the': 6548,


In [ ]:
np.where(X_train_np[0]!=0)

(array([ 106,  484,  938, 1064, 1557, 2849, 2872, 2924, 3482, 3601, 4285,
        5050, 6565, 6938, 7092, 7430]),)

In [ ]:
X_train_np[0][5104]

0

In [ ]:
X_test_cv = v.transform(X_test)

In [ ]:
print(X_train_cv.shape)
print(y_train.shape)

(4179, 7472)
(4179,)


In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

Evaluation

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
y_pred= model.predict(X_test_cv)
print (classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      1212
           1       0.98      0.91      0.94       181

    accuracy                           0.99      1393
   macro avg       0.98      0.95      0.97      1393
weighted avg       0.99      0.99      0.99      1393

